spring:
  application:
    name: rest_with_spring_boot_and_java
  datasource:
    url: jdbc:mysql://localhost:3306/rest_with_spring_boot_and_java?useSSL=false&serverTimezone=UTC
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 124356
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQL8Dialect
